version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "15432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@a.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge
